version: "3"

services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      - EULA=TRUE
      - MEMORY=2G
      - TYPE=FORGE
      - VERSION=1.17.1
      - FORGEVERSION=37.1.1
      - ENABLE_WHITELIST=TRUE
      - DIFFICULTY=normal
      - ENABLE_COMMAND_BLOCK=FALSE
      - ENABLE_RCON=FALSE
      - TZ=Asia/Tokyo
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data